const THROW_EXCEPTION = {
  UNKNOWN: 'Unknown error! Please try again later.',
  NETWORK_CONGESTED: 'The network may be congested. Please try again later.',
  ONCHAIN_TIMEOUT:
    'The transaction is taking too long time. Please try again later.',
  USER_REJECTED_REQUEST: 'User rejected the request.',
};

export { THROW_EXCEPTION };
